version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dauletbaev/php-app
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
      - phpmyadmin

  webserver:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    image: dauletbaev/php-nginx
    restart: unless-stopped
    ports:
      - "5000:80"
    volumes:
      - ./src:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file:
      - env/mysql.env
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8082:80"
    env_file:
      - env/phpmyadmin.env

volumes:
  dbdata:
