version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
      - phpmyadmin

  webserver:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    restart: unless-stopped
    ports:
      - "5000:80"
    volumes:
      - ./src:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file:
      - env/mysql.env
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:fpm-alpine
    volumes:
      - phpmyadmin_data:/var/www/html
      - /sessions
    depends_on:
      - db
    env_file:
      - env/phpmyadmin.env
  
  nginxforphpmyadmin:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./config/phpmyadmin.nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - phpmyadmin_data:/var/www/html/:ro
    ports:
      - "8000:80"

volumes:
  dbdata:
  phpmyadmin_data:
